import type { ConstructionTrace } from "./types";

export const polynomialConstructionTrace: ConstructionTrace = {
  nodes: [
    {
      id: "node-a",
      kind: "given",
      label: "a",
      expressionLatex: "a",
      inputs: [],
      output: "segment-a",
    },
    {
      id: "node-b",
      kind: "given",
      label: "b",
      expressionLatex: "b",
      inputs: [],
      output: "segment-b",
    },
    {
      id: "node-unit",
      kind: "constant",
      label: "unit",
      expressionLatex: "1",
      inputs: [],
      output: "segment-unit",
    },
    {
      id: "node-x",
      kind: "add",
      label: "x = 3a + b",
      expressionLatex: "x=3a+b",
      inputs: ["node-a", "node-b"],
      output: "segment-x",
    },
    {
      id: "node-y",
      kind: "add",
      label: "y = a + b",
      expressionLatex: "y=a+b",
      inputs: ["node-a", "node-b"],
      output: "segment-y",
    },
    {
      id: "node-r",
      kind: "mul",
      label: "r = xy",
      expressionLatex: "r=xy",
      inputs: ["node-x", "node-y", "node-unit"],
      output: "segment-result",
    },
  ],
  steps: [
    {
      id: "step-givens",
      level: "macro",
      title: "Place the given lengths",
      summary: "Place a, b, and the fixed unit segment.",
      operation: "given",
      inputObjectIds: [],
      outputObjectIds: ["segment-a", "segment-b", "segment-unit"],
      createdObjectIds: ["segment-a", "segment-b", "segment-unit"],
    },
    {
      id: "step-x",
      level: "macro",
      title: "Construct x = 3a + b",
      summary: "Transfer three copies of a followed by b.",
      operation: "add",
      inputObjectIds: ["segment-a", "segment-b"],
      outputObjectIds: ["segment-x"],
      createdObjectIds: ["segment-x"],
    },
    {
      id: "step-y",
      level: "macro",
      title: "Construct y = a + b",
      summary: "Transfer b after a on the result ray.",
      operation: "add",
      inputObjectIds: ["segment-a", "segment-b"],
      outputObjectIds: ["segment-y"],
      createdObjectIds: ["segment-y"],
    },
    {
      id: "step-result",
      level: "macro",
      title: "Construct r = x · y",
      summary: "Use similar triangles to scale y by x relative to the unit.",
      operation: "mul",
      inputObjectIds: ["segment-x", "segment-y", "segment-unit"],
      outputObjectIds: ["segment-result"],
      createdObjectIds: ["segment-result"],
      proofId: "proof-product",
    },
  ],
  revealActions: [
    {
      id: "reveal-result",
      stepId: "step-result",
      objectId: "segment-result",
      start: 0,
      end: 1,
      animation: "draw",
    },
  ],
  proofs: [
    {
      id: "proof-product",
      title: "Similar-triangle multiplication",
      operation: "mul",
      intuition: "Parallel lines preserve the ratio set by the unit segment.",
      givens: ["OU = 1", "OX = x", "OY = y"],
      claims: [
        {
          id: "claim-product",
          text: "The corresponding triangles are similar.",
          mathLatex: "OZ/OY=OX/OU",
          highlightObjectIds: [
            "segment-unit",
            "segment-x",
            "segment-y",
            "segment-result",
          ],
        },
      ],
      conclusion: "OZ = xy",
    },
  ],
};
